
services:
  web:
    build: .
    volumes:
      - ./:/app:cached  # Mount the app folder with cached access mode
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=gandalf
      - MYSQL_PASSWORD=youShallNotPass
      - MYSQL_DATABASE=moria
    depends_on:
      - db
    command: node index.js

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=moria
      - MYSQL_USER=gandalf
      - MYSQL_PASSWORD=youShallNotPass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: